import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NoFlash from "../components/NoFlash";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" style={{ visibility: 'hidden' }}>
      <head>
        {/* 预加载样式 */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NoFlash />
        {children}
      </body>
    </html>
  );
}
